version: '3.8'

services:
  app:
    build: .
    command: ["sh", "-c", "./bin/rails server -b 0.0.0.0"]
    volumes:
      - ".:/app"
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
    depends_on:
      - db
    working_dir: /app
    networks:
      - app-network

  db:
    image: nouchka/sqlite3:latest
    volumes:
      - db:/app/db
    networks:
      - app-network

volumes:
  db:

networks:
  app-network:
    driver: bridge
